config/routes.rb
Rails.application.routes.draw do

  get 'umsg/show'

  resources :eventcals
  resources :charges
  resources :phistories
  resources :authors
  resources :presentations
  #get 'eventcals/show'
  devise_for :users
  root 'presentations#index'
  #devise_scope :user do
   # root to: "devise/registrations#edit"
  #end
end

app/models/presentation.rb
class Presentation < ApplicationRecord
  has_and_belongs_to_many :users
  #belongs_to :author
  #belongs_to :course
end

app/controllers/presentations_controller.rb
require 'notifyuser'
require 'notifyuserobserver'
class PresentationsController < ApplicationController
  before_action :set_presentation, only: [:show, :edit, :update, :destroy]
  before_action :inbef, only: [:index]
  
  # GET /presentations
  # GET /presentations.json
  def index
    @presentations = Presentation.all
    if params[:topic] == "all"
      @presentations = Presentation.all
    elsif params[:topic] != nil
      @presentations = Presentation.where(:id => params[:topic])
    end
    @obj = Notifyuser.new
    @obj.subscribe(Notifyuserobserver.new)
    if user_signed_in?
         current_user.analyse = params[:intd]
         current_user.save
    end
  end

  # GET /presentations/1
  # GET /presentations/1.json
  def show
  end

  # GET /presentations/new
  def new
    @presentation = Presentation.new
    @courses = Course.all.map{ |c| [c.ctype, c.id] }
    @authors = Author.all.map{ |c| [c.aname, c.id] }
  end

  # GET /presentations/1/edit
  def edit
     @authors = Author.all.map{ |c| [c.aname, c.id] }
     @courses = Course.all.map{ |c| [c.ctype, c.id] }
  end

  # POST /presentations
  # POST /presentations.json
  def create
    @authors = Author.all.map{ |c| [c.aname, c.id] }
    @courses = Course.all.map{ |c| [c.ctype, c.id] }
    if current_user.course_id !=0
        @presentation = Presentation.new(presentation_params)
        @author = Author.find_by id: params[:author_id]
        @course = Course.find_by id: params[:course_id]
        if @author == nil
          @presentation.author_id = 0
        else
          @presentation.author_id = @author.id
        end
        @presentation.course_id = @course.id
        respond_to do |format|
          if @presentation.save
            format.html { redirect_to @presentation, notice: 'Presentation was successfully created.' }
            format.json { render :show, status: :created, location: @presentation }
          else
            format.html { render :new }
            format.json { render json: @presentation.errors, status: :unprocessable_entity }
          end
        end
    else
      @course = Course.find_by id: params[:course_id]
      current_user.course_id = @course.id
      
      if current_user.save
        format.html { redirect_to @presentation, notice: 'Presentation was successfully created.' }
        format.json { render :show, status: :created, location: @presentation }
      else
        format.html { render :new }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presentations/1
  # PATCH/PUT /presentations/1.json
  def update
    @courses = Course.all.map{ |c| [c.ctype, c.id] }
    @authors = Author.all.map{ |c| [c.aname, c.id] }
    
      
      if current_user.course_id !=0
          @author = Author.find_by id: params[:author_id]
          @course = Course.find_by id: params[:course_id]
          if @author != nil
            @presentation.author_id = @author.id
          end
          if @course != nil
            @presentation.course_id = @course.id
          end
          respond_to do |format|
            if @presentation.update(presentation_params)
              format.html { redirect_to @presentation, notice: 'Presentation was successfully updated.' }
              format.json { render :show, status: :ok, location: @presentation }
            else
              format.html { render :edit }
              format.json { render json: @presentation.errors, status: :unprocessable_entity }
            end
          end
      else
        @course = Course.find_by id: params[:course_id]
        current_user.course_id = @course.id
        if current_user.save
          format.html { redirect_to @presentation, notice: 'Presentation was successfully created.' }
          format.json { render :show, status: :created, location: @presentation }
        else
          format.html { render :new }
          format.json { render json: @presentation.errors, status: :unprocessable_entity }
        end
      end
  end

  # DELETE /presentations/1
  # DELETE /presentations/1.json
  def destroy
    @presentation.destroy
    respond_to do |format|
      format.html { redirect_to presentations_url, notice: 'Presentation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation
      @presentation = Presentation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presentation_params
      params.require(:presentation).permit(:name, :descrip, :dt, :locat, :course_id, :author_id)
    end
    
    def inbef
        @presentations = Presentation.all
        @phistories = Phistory.all
        @allow = true
        @ptid = 0
        
        @presentations.each do |presentation|
          @phistories.each do |phistory|
            if phistory.hlocat == presentation.name
              if user_signed_in?
                if phistory.user_id == current_user.id
                  @allow = false
                  @ptid = presentation.id
                end
              end
            end
          end
        end
    end
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/views/presentations/_form.html.erb
<% if presentation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(presentation.errors.count, "error") %> prohibited this presentation from being saved:</h2>
    
        <ul>
            <% presentation.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
        </ul>
      </div>

<% else %>
  <% if current_user.course_id == 0 %>
          <div>
              <%= simple_form_for  @presentation, :html => { :multipart => true } do |f| %>
                <%= select_tag(:course_id, options_for_select(@courses), :prompt => "Select Course") %>
                <%= f.button :submit %>  
              <% end %>
          </div>
  <% else %>
          <div>
            <%= simple_form_for  @presentation, :html => { :multipart => true } do |f| %>
              <%= f.input :name, label: "Presentation Name", id: :presentation_name %>
              <%= f.text_area :descrip, label: "Description", id: :presentation_descrip %>
              <%= f.datetime_select :dt, label: "Date and Time", id: :presentation_dt %>
              <%= f.input :locat, label: "Location", id: :presentation_locat %>
              <%= select_tag(:course_id, options_for_select(@courses), :prompt => "Select Course") %>
              <%= select_tag(:author_id, options_for_select(@authors), :prompt => "Select Author") %>
              <%= f.button :submit %>   
            <% end %>
          </div>
  <% end %>

<% end %>

app/views/presentations/edit.html.erb
<h1>Editing Presentation</h1>
<% if user_signed_in? && current_user.admin? %>    
      <%= render 'form', presentation: @presentation %>
      
      <%= link_to 'Show', @presentation %> 
<% else %>
  <h1> Login to get access to the information </h1>
<% end %>
<%= link_to 'Back', presentations_path %>

app/views/presentations/index.html.erb
<% if user_signed_in? %>
        <div class="row">
          <div class="col-md-10">
            <h5><%= link_to 'Display All Presentations', presentations_path(:topic => "all") %></h5> 
            <h5><%= link_to 'Display My Presentations', presentations_path(:topic => current_user.course_id) %></h5>
            <h5><%= link_to 'EVENT CALENDAR', eventcals_path(:pid => @ptid) %></h5>
            <h5><%= link_to 'Message', umsg_show_path %></h5>
          </div>
          <div class="col-md-10">
            <h5>Get messages when the cost is reduced for the selected area of interest</h5>
            <h5><%= link_to 'Interested', presentations_path(:intd => true) %></h5>
            <h5><%= link_to 'Not Interested', presentations_path(:intd => false) %></h5>
          </div>
        </div>
       
  <% if current_user.course_id == 0 %>
    <h1> Select your required Course before getting to know about the presentations </h1>
    <p><%= link_to 'Select Course', new_presentation_path %></p>
  <% else %>
        <% if @presentations.count == 0 %>
            <h1> No Presentation Details to be displayed </h1>
            <% if current_user.admin? %>
               <%= link_to 'New Presentation', new_presentation_path %>
            <% end %>
        <% else %>
            <div class="row">
                <div class="col-md-10">
                  <h1>Presentation Details</h1>
      
                  <table>
                    <thead>
                      <tr>
                        <th>PRESENTATION NAME</th>
                        <th>AUTHOR DETAILS</th>
                        <th>DESCRIPTION</th>
                        <th>DATE AND TIME</th>
                        <th>LOCATION DETAILS</th>
                        <th>COST DETAILS</th>
                        <th>ATTENDING</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>
            </div>
                </div>
      
            <div class="row">
                <div class="col-md-10">
                    <tbody>
                      <% @presentations.each do |presentation| %>
                        <% @author = Author.find_by id: presentation.author_id %>
                        <% @pcost = Pcost.find_by id: @author.pcost_id %>
                        <tr>
                          <td><%= presentation.name %></td>
                          <td><%= @author.aname %><br /><%= link_to 'Get Details', author_path(presentation.author_id) %></td>
                          <td><%= presentation.descrip %></td>
                          <td><%= presentation.dt %></td>
                          <td><%= presentation.locat %></td>
                          <td><%= @pcost.cost %> <h10>Euroes</h10></td>
                          <% if current_user.analyse == true %>
                            <% @obj.ucall(@pcost.id,presentation) %>
                          <% end %>
                          <td><%= presentation.attending %></td>
                          <td><%= link_to 'Show', presentation %></td>
                          <td>
                            <%= form_tag new_phistory_path(params[:id]), :method => "get" do %>
                                <div>
                                    <input id="cost" name="cost" type="hidden" value="<%= @pcost.cost  %>" />
                                    <input id="pt" name="pt" type="hidden" value="<%= presentation.id  %>" />
                                    <% if @allow %>
                                      <button type="submit" class="btn btn-default btn-lg">Pay Now</button>
                                    <% else %>
                                      <button type="submit" disabled="disabled" class="btn btn-default btn-lg">Pay Now</button>
                                    <% end %>
                                 </div>
                            <% end %>
                          </td>
                          <% if current_user.admin? %>
                            <td><%= link_to 'Edit', edit_presentation_path(presentation) %></td>
                            <td><%= link_to 'Destroy', presentation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                          <% end %>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
      
                  <br>
            </div>
                </div>
                
          <% end %>
    <% end %>
<% else %>
  <h1> Sign In to know more details about the presentations by clicking the below link </h1>
  <%= link_to 'Get Access', new_user_session_path %>
<% end %>

app/views/presentations/new.html.erb
<h1>New Presentation</h1>
<% if user_signed_in? %>
  <%= render 'form', presentation: @presentation %>
<% else %>
  <h1> Login to get access to the information </h1>
<% end %>
<%= link_to 'Back', presentations_path %>

app/views/presentations/show.html.erb
<div class="row">
  <div class="col-md-10">
    <% if user_signed_in? %>
            <p>
              <strong>Presentation Name:</strong>
              <%= @presentation.name %>
            </p>

            <p>
              <strong>Description:</strong>
              <%= @presentation.descrip %>
            </p>

            <p>
              <strong>Date and Time:</strong>
              <%= @presentation.dt %>
            </p>

            <p>
              <strong>Location:</strong>
              <%= @presentation.locat %>
            </p>
          <% if current_user.admin? %>
            <%= link_to 'Edit', edit_presentation_path(@presentation) %> 
          <% end %>
            <%= link_to 'Back', presentations_path %>
    <% else %>
          <h1> Login to get to know more details about your selected course presentations </h1>
    <% end %>
  </div>
</div>