config/routes.rb
Rails.application.routes.draw do

  get 'umsg/show'

  resources :eventcals
  resources :charges
  resources :phistories
  resources :authors
  resources :presentations
  #get 'eventcals/show'
  devise_for :users
  root 'presentations#index'
  #devise_scope :user do
   # root to: "devise/registrations#edit"
  #end
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :presentations
  #belongs_to :pcost
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
    @pcosts = Pcost.all.map{ |c| [c.cost, c.id] }
  end

  # GET /authors/1/edit
  def edit
    @pcosts = Pcost.all.map{ |c| [c.cost, c.id] }
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)
    @pcosts = Pcost.all.map{ |c| [c.cost, c.id] }
    @pcost = Pcost.find_by id: params[:pcost_id]
    if @pcost == nil
      @author.pcost_id = 0
    else
      @author.pcost_id = @pcost.id
    end

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    @pcosts = Pcost.all.map{ |c| [c.cost, c.id] }
    @pcost = Pcost.find_by id: params[:pcost_id]
    if @pcost == nil
      @author.pcost_id = 0
    else
      @author.pcost_id = @pcost.id
    end
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:aname, :courses, :workexp, :descript)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<% if author.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>
    
        <ul>
            <% author.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
        </ul>
      </div>

<% else %>
          <div>
            <%= simple_form_for  @author, :html => { :multipart => true } do |f| %>
              <%= f.input :aname, label: "Author Name", id: :author_aname %>
              <%= f.text_area :courses, label: "Courses Done", id: :author_courses %>
              <%= f.input :workexp, label: "Work Experience", id: :author_workexp %>
              <%= f.text_area :descript, label: "Description", id: :author_descript %>
              <%= select_tag(:pcost_id, options_for_select(@pcosts), :prompt => "Select Cost") %>
              <%= f.button :submit %>   
            <% end %>
          </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>
<% if user_signed_in? && current_user.admin? %>    
      <%= render 'form', author: @author %>
      
      <%= link_to 'Show', @author %> 
<% else %>
  <h1> Login to get access to the information </h1>
<% end %>
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<% if user_signed_in? %>
            <h1>Authors</h1>
    <% if @authors.count == 0 %>
      <h1> No Available Authors </h1>
      <% if current_user.admin? %>
               <%= link_to 'New Author', new_author_path %>
      <% end %>
    <% else %>
           <div class="row">
                <div class="col-md-10">
                  <h1>Author Details</h1>
      
                  <table>
                    <thead>
                      <tr>
                        <th>Author Name</th>
                        <th>Courses</th>
                        <th>Work Experience</th>
                        <th>Description</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>
            </div>
                </div>
      
            <div class="row">
                <div class="col-md-10">
                    <tbody>
                      <% @authors.each do |author| %>
                        <tr>
                          <td><%= author.aname %></td>
                          <td><%= author.courses %></td>
                          <td><%= author.workexp %></td>
                          <td><%= author.descript %></td>
                          <td><%= link_to 'Show', author %></td>
                          <% if current_user.admin? %>
                            <td><%= link_to 'Edit', edit_author_path(author) %></td>
                            <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                          <% end %>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
      
                  <br>
            </div>
                </div>
    <% end %>    
<% end %>

app/views/authors/new.html.erb
<h1>New Author</h1>
<% if user_signed_in? %>
  <%= render 'form', author: @author %>
<% else %>
  <h1> Login to get access to the information </h1>
<% end %>
<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<div class="row">
  <div class="col-md-10">
    <% if user_signed_in? %>
            <p>
              <strong>Author Name:</strong>
              <%= @author.aname %>
            </p>

            <p>
              <strong>Courses</strong>
              <%= @author.courses %>
            </p>

            <p>
              <strong>Work Experience</strong>
              <%= @author.workexp %>
            </p>

            <p>
              <strong>Description:</strong>
              <%= @author.descript %>
            </p>
          <% if current_user.admin? %>
            <%= link_to 'Edit', edit_author_path(@author) %> 
          <% end %>
            <%= link_to 'Back', authors_path %>
    <% else %>
          <h1> Login to get to know more details about your selected course authors </h1>
    <% end %>
  </div>
</div>